### ISSUE TITLE
'done' channel in README not used

### ISSUE THREAD

**Issue by ForrestWeston** [howeyc/fsnotify#111]
I was trying to figure out how your package worked (I am still new to Go) and I noticed that the 'done' channel in the README doesn't actually do anything. Should this be removed or is there a purpose for it?

**Comment by howeyc** [comment]
It's there so the demo/test/template program doesn't terminate. That way you can keep the watcher program up and edit/modify files you are watching to see the events as they come in.

In an actual application, no it's not necessary.

**Comment by ForrestWeston** [comment]
Alright, that makes sense, thank you. Do you mind if I PR in a comment explaining that?

**Comment by howeyc** [comment]
sure
