### ISSUE TITLE
Separate goroutine?

### ISSUE THREAD

**Issue by ManuelAmadorAditazz** [howeyc/fsnotify#38]
In your readme you say: Do I have to watch the Error and Event channels in a separate goroutine?
As of now, yes. Looking into making this single-thread friendly.

But the example code right above it only runs a single goroutine:

```
go func() {
    for {
        select {
        case ev := <-watcher.Event:
            log.Println("event:", ev)
        case err := <-watcher.Error:
            log.Println("error:", err)
        }
    }
}()
```

What gives?

**Comment by mmmikelee** [comment]
A goroutine uses select to monitor the watcher channels.
Should the select NOT include other channels from my program?
Should the watcher channels have their own goroutine and my other channels in another goroutine?
