### ISSUE TITLE
Anyone got this working with Google App Engine?

### ISSUE THREAD

**Issue by metaleap** [howeyc/fsnotify#48]
I'm a big fan of this package, especially how it _just-works_ even under Windows!  ;)

So no probs in my local dev environment, Win7, Go 1.1 64-bit.

Now I tried to upload a simple web app to Google App Engine, which runs on Linux 64-bit but sadly only Go 1.0.3. My app won't compile because 6g fails to compile the **fsnotify** package:

```
11:04 PM Compilation starting.
11:04 PM Compilation: 35 files left.
11:04 PM Error 422: --- begin server output ---
Compile failed:
2013/06/04 14:04:26 go-app-builder: Failed building app: failed running 6g: exit status 1

github.com/howeyc/fsnotify/fsnotify.go:20: undefined: Watcher
--- end server output ---
```

So I'm wondering whether this is due to GAE using Go 1.0.3, or just due to the sandboxed restrictions at GAE... @howeyc have you ever used this on GAE or know any fsnotify users who successfully have?

**Comment by kadamvandita** [comment]
I am getting similar issue with my istioctl build.Any progress or solution to this?
